"""create models

Revision ID: 7b5a11531e1b
Revises: 
Create Date: 2026-07-19 11:48:00.187902
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b5a11531e1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cns', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paciente_cpf'), ['cpf'], unique=True)

    op.create_table('senha',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_atendimento', sa.Enum('AGENDADA', 'ESPONTANEA', 'VACINACAO', name='tipoatendimento'), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO', 'CHAMADA', 'FINALIZADA', 'CANCELADA', name='statussenha'), nullable=False),
    sa.Column('data_hora_emissao', sa.DateTime(), nullable=False),
    sa.Column('data_hora_chamada', sa.DateTime(), nullable=True),
    sa.Column('paciente_id', sa.Uuid(), nullable=True),
    sa.Column('status_sincronizacao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('senha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senha_codigo'), ['codigo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte a migração."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senha_codigo'))

    op.drop_table('senha')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paciente_cpf'))

    op.drop_table('paciente')
    # ### end Alembic commands ###
